apiVersion: v1
kind: Service
metadata:
  name: module-a
  labels:
    app: module-a
    service: module-a
spec:
  ports:
    - port: 8001
      name: http
  selector:
    app: module-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-sample-module-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-a-v1
  labels:
    app: module-a
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: module-a
      version: v1
  template:
    metadata:
      labels:
        app: module-a
        version: v1
    spec:
      serviceAccountName: istio-sample-module-a
      containers:
        - image: okeyja/istio-sample-module-a:1.0.0
          imagePullPolicy: Always
          name: istio-sample-module-a
          ports:
            - containerPort: 8001
